#!/usr/bin/env bash

port=5029

indent() {
  sed -u 's/^/       /'
}

if [ -z "$LOCALTONET_API_TOKEN" ]; then
  echo "You must set the LOCALTONET_API_TOKEN config var to create a UDP tunnel!"
  exit 1
fi

# Download LocalToNet
echo -n "-----> Installing localtonet... "
curl --silent -o localtonet.zip -L "https://localtonet.com/download/localtonet-linux-x64.zip" | indent
unzip localtonet.zip -d ./ > /dev/null 2>&1
chmod +x ./localtonet
echo "done"

# Start the UDP tunnel
echo -n "-----> Starting localtonet... "
localtonet_cmd="./localtonet authtoken $LOCALTONET_API_TOKEN"
eval "$localtonet_cmd | tee localtonet.log &"
echo "done"

mkdir /app/.srb2kart/
find /app/ -type f -execdir cp "{}" /app/.srb2kart/ ";"

cp /app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so /app/.apt/usr/lib/x86_64-linux-gnu/libpulsecommon-13.99.so
rm -rf /app/.apt/usr/lib/x86_64-linux-gnu/pulseaudio/

echo "Starting SRB2Kart"
/app/.dpkg/usr/games/SRB2Kart/srb2kart -dedicated -port ${port}